### ISSUE TITLE
Error while initializing an environment [Windows]

### ISSUE THREAD

**Issue by acl21** [openai/safety-gym#14]
I am unable to initialize the environment on windows. 

### System Information
* Windows 10
* Python 3.9
* safety-gym==0.0.0, gym==0.15.7, mujoco_py==2.0.2.7, numpy==1.17.5. 
* All requirements are installed correctly.

### Code to reproduce
```python
import safety_gym
import gym

env = gym.make('Safexp-PointGoal1-v0')
```

### Error Message
```
>>> env = gym.make('Safexp-PointGoal1-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\apps\Anaconda3\envs\dll\lib\site-packages\gym\envs\registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "D:\apps\Anaconda3\envs\dll\lib\site-packages\gym\envs\registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "D:\apps\Anaconda3\envs\dll\lib\site-packages\gym\envs\registration.py", line 73, in make
    env = cls(**_kwargs)
  File "D:\apps\Anaconda3\envs\dll\Lib\site-packages\safety-gym\safety_gym\envs\engine.py", line 316, in __init__
    self.seed(self._seed)
  File "D:\apps\Anaconda3\envs\dll\Lib\site-packages\safety-gym\safety_gym\envs\engine.py", line 551, in seed
    self._seed = np.random.randint(2**32) if seed is None else seed
  File "mtrand.pyx", line 628, in numpy.random.mtrand.RandomState.randint
  File "bounded_integers.pyx", line 1318, in numpy.random.bounded_integers._rand_int32
ValueError: high is out of bounds for int32
```

**Comment by acl21** [comment]
I found the cause and a quick fix [here](https://github.com/SimonBlanke/Gradient-Free-Optimizers/issues/11). Apparently numpy defaults to int64 on Linux but to int32 on Windows.

Simply changing line 551 in `engine.py` to the following works:
```python
self._seed = np.random.randint(2**32-2, dtype=np.int64) if seed is None else seed
```
