### ISSUE TITLE
Error during installation: Building wheel for mujoco-py (PEP 517)

### ISSUE THREAD

**Issue by chisness** [openai/safety-gym#2]
I successfully installed MuJoCo using `pip3 install -U 'mujoco-py<2.1,>=2.0'`

I got this warning, but it still installed fine and works:
```
  WARNING: Missing build requirements in pyproject.toml for mujoco-py<2.1,>=2.0 from https://files.pythonhosted.org/packages/a2/30/21abd0cf2734bf5f34a7a8967789b12dee55f1e51e9c1c60af1cba549123/mujoco-py-2.0.2.9.tar.gz#sha256=6ae20ca9509203758f5e30a7a4019cb2d581b6d40dc2c2669dbe3229cfdf05e8.
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
```
When I try to install safety-gym with `pip3 install -e .`, I get the same warning as above, but then I get an error. At the end it says HINT: On OS X, install GCC with `brew install gcc`, but gcc is already installed and up to date. Reinstalling did not help. Any advice? 

Here is the entire output:

```
Collecting gym~=0.15.3
  Using cached https://files.pythonhosted.org/packages/1d/85/a7a462d7796f097027d60f9a62b4e17a0a94dcf12ac2a9f9a913333b11a6/gym-0.15.4.tar.gz
Collecting joblib~=0.14.0
  Using cached https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl
Collecting mujoco_py==2.0.2.7
  Using cached https://files.pythonhosted.org/packages/c3/a1/00f5482d6325565f35a81707b8c6b3e364bdc8f7b9487c15c18781e1432a/mujoco-py-2.0.2.7.tar.gz
  Installing build dependencies ... done
  WARNING: Missing build requirements in pyproject.toml for mujoco_py==2.0.2.7 from https://files.pythonhosted.org/packages/c3/a1/00f5482d6325565f35a81707b8c6b3e364bdc8f7b9487c15c18781e1432a/mujoco-py-2.0.2.7.tar.gz#sha256=2a294006c66ed225c3409b9d60a91afeb7756f96fecf3d8c22116d00adf6d82a (from safety-gym==0.0.0).
  WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting numpy~=1.17.4
  Using cached https://files.pythonhosted.org/packages/9e/cf/7cea38d32df6087d7c15bca8edef0be82e0d957119e9dafd7052dc6192f0/numpy-1.17.4-cp38-cp38-macosx_10_9_x86_64.whl
Collecting xmltodict~=0.12.0
  Using cached https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
Collecting scipy
  Using cached https://files.pythonhosted.org/packages/90/d2/44b70a930ad28da8f65d8c294ac88b20f561e5d650b85efea80381566db1/scipy-1.4.1-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from gym~=0.15.3->safety-gym==0.0.0) (1.13.0)
Collecting pyglet<=1.3.2,>=1.2.0
  Using cached https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl
Collecting cloudpickle~=1.2.0
  Using cached https://files.pythonhosted.org/packages/c1/49/334e279caa3231255725c8e860fa93e72083567625573421db8875846c14/cloudpickle-1.2.2-py2.py3-none-any.whl
Collecting opencv-python
  Using cached https://files.pythonhosted.org/packages/c8/e8/bcef356c7f89433a5f4e631bbe898d03ba79d1c06a5d779829a10ddf16e8/opencv_python-4.1.2.30-cp38-cp38-macosx_10_9_x86_64.whl
Requirement already satisfied: imageio>=2.1.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (2.6.1)
Requirement already satisfied: Cython>=0.27.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (0.29.14)
Requirement already satisfied: glfw>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (1.8.7)
Requirement already satisfied: cffi>=1.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (1.13.2)
Requirement already satisfied: fasteners~=0.15 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (0.15)
Collecting future
  Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from imageio>=2.1.2->mujoco_py==2.0.2.7->safety-gym==0.0.0) (6.2.1)
Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from cffi>=1.10->mujoco_py==2.0.2.7->safety-gym==0.0.0) (2.19)
Requirement already satisfied: monotonic>=0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from fasteners~=0.15->mujoco_py==2.0.2.7->safety-gym==0.0.0) (1.5)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/tmpv4_0jd48
       cwd: /private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py
  Complete output (49 lines):
  running bdist_wheel
  running build
  Removing old mujoco_py cext /private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/generated/cymj_2.0.2.7_38_macextensionbuilder_38.so
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 181, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 208, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
      self.run_setup()
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 236, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 33, in <module>
      setup(
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 29, in run
      import mujoco_py  # noqa: force build
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
      from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 506, in <module>
      cymj = load_cython_ext(mujoco_path)
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 105, in load_cython_ext
      cext_so_path = builder.build()
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 221, in build
      built_so_file_path = self._build_impl()
    File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 324, in _build_impl
      raise RuntimeError(
  RuntimeError: Could not find GCC executable.
  
  HINT: On OS X, install GCC with `brew install gcc`. or `port install gcc`.
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
ERROR: Could not build wheels for mujoco-py which use PEP 517 and cannot be installed directly
```

**Comment by bbalaji-ucsd** [comment]
+1

**Comment by chisness** [comment]
This worked after installing an older version of gcc

**Comment by bbalaji-ucsd** [comment]
Thanks! I got the error fixed after following the troubleshooting instructions for Mac in mujoco-py

**Comment by xkianteb** [comment]
change setup mujoco-py version from 2.0.2.7 to 2.0.2.5; 2.0.2.7 has not been released yet

**Comment by Semisens** [comment]
Which version of gcc did you use ?

**Comment by chisness** [comment]
4.2.1 now

**Comment by Semisens** [comment]
thx

**Comment by M-Aali** [comment]
I have a similar problem, how did you downgrade to an older gcc version?

**Comment by fbarez** [comment]
I have faced the same issue. The above did not work for me. Has anyone found a solution? Thanks

**Comment by Semisens** [comment]
If you're trying tu use opencv with cuda, forget python and use c++ opencv::cuda libraries

**Comment by fbarez** [comment]
The problem is with installing safety-gym.
  ERROR: Failed building wheel for mujoco-py

**Comment by fbarez** [comment]
macOS users: this error is cases by mujoco's c compiler. There is no symbolic link between gcc and clang.

**Comment by fbarez** [comment]
> I successfully installed MuJoCo using `pip3 install -U 'mujoco-py<2.1,>=2.0'`
> 
> I got this warning, but it still installed fine and works:
> 
> ```
>   WARNING: Missing build requirements in pyproject.toml for mujoco-py<2.1,>=2.0 from https://files.pythonhosted.org/packages/a2/30/21abd0cf2734bf5f34a7a8967789b12dee55f1e51e9c1c60af1cba549123/mujoco-py-2.0.2.9.tar.gz#sha256=6ae20ca9509203758f5e30a7a4019cb2d581b6d40dc2c2669dbe3229cfdf05e8.
>   WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
> ```
> 
> When I try to install safety-gym with `pip3 install -e .`, I get the same warning as above, but then I get an error. At the end it says HINT: On OS X, install GCC with `brew install gcc`, but gcc is already installed and up to date. Reinstalling did not help. Any advice?
> 
> Here is the entire output:
> 
> ```
> Collecting gym~=0.15.3
>   Using cached https://files.pythonhosted.org/packages/1d/85/a7a462d7796f097027d60f9a62b4e17a0a94dcf12ac2a9f9a913333b11a6/gym-0.15.4.tar.gz
> Collecting joblib~=0.14.0
>   Using cached https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl
> Collecting mujoco_py==2.0.2.7
>   Using cached https://files.pythonhosted.org/packages/c3/a1/00f5482d6325565f35a81707b8c6b3e364bdc8f7b9487c15c18781e1432a/mujoco-py-2.0.2.7.tar.gz
>   Installing build dependencies ... done
>   WARNING: Missing build requirements in pyproject.toml for mujoco_py==2.0.2.7 from https://files.pythonhosted.org/packages/c3/a1/00f5482d6325565f35a81707b8c6b3e364bdc8f7b9487c15c18781e1432a/mujoco-py-2.0.2.7.tar.gz#sha256=2a294006c66ed225c3409b9d60a91afeb7756f96fecf3d8c22116d00adf6d82a (from safety-gym==0.0.0).
>   WARNING: The project does not specify a build backend, and pip cannot fall back to setuptools without 'wheel'.
>   Getting requirements to build wheel ... done
>   Installing backend dependencies ... done
>     Preparing wheel metadata ... done
> Collecting numpy~=1.17.4
>   Using cached https://files.pythonhosted.org/packages/9e/cf/7cea38d32df6087d7c15bca8edef0be82e0d957119e9dafd7052dc6192f0/numpy-1.17.4-cp38-cp38-macosx_10_9_x86_64.whl
> Collecting xmltodict~=0.12.0
>   Using cached https://files.pythonhosted.org/packages/28/fd/30d5c1d3ac29ce229f6bdc40bbc20b28f716e8b363140c26eff19122d8a5/xmltodict-0.12.0-py2.py3-none-any.whl
> Collecting scipy
>   Using cached https://files.pythonhosted.org/packages/90/d2/44b70a930ad28da8f65d8c294ac88b20f561e5d650b85efea80381566db1/scipy-1.4.1-cp38-cp38-macosx_10_9_x86_64.whl
> Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from gym~=0.15.3->safety-gym==0.0.0) (1.13.0)
> Collecting pyglet<=1.3.2,>=1.2.0
>   Using cached https://files.pythonhosted.org/packages/1c/fc/dad5eaaab68f0c21e2f906a94ddb98175662cc5a654eee404d59554ce0fa/pyglet-1.3.2-py2.py3-none-any.whl
> Collecting cloudpickle~=1.2.0
>   Using cached https://files.pythonhosted.org/packages/c1/49/334e279caa3231255725c8e860fa93e72083567625573421db8875846c14/cloudpickle-1.2.2-py2.py3-none-any.whl
> Collecting opencv-python
>   Using cached https://files.pythonhosted.org/packages/c8/e8/bcef356c7f89433a5f4e631bbe898d03ba79d1c06a5d779829a10ddf16e8/opencv_python-4.1.2.30-cp38-cp38-macosx_10_9_x86_64.whl
> Requirement already satisfied: imageio>=2.1.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (2.6.1)
> Requirement already satisfied: Cython>=0.27.2 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (0.29.14)
> Requirement already satisfied: glfw>=1.4.0 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (1.8.7)
> Requirement already satisfied: cffi>=1.10 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (1.13.2)
> Requirement already satisfied: fasteners~=0.15 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from mujoco_py==2.0.2.7->safety-gym==0.0.0) (0.15)
> Collecting future
>   Using cached https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz
> Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from imageio>=2.1.2->mujoco_py==2.0.2.7->safety-gym==0.0.0) (6.2.1)
> Requirement already satisfied: pycparser in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from cffi>=1.10->mujoco_py==2.0.2.7->safety-gym==0.0.0) (2.19)
> Requirement already satisfied: monotonic>=0.1 in /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages (from fasteners~=0.15->mujoco_py==2.0.2.7->safety-gym==0.0.0) (1.5)
> Building wheels for collected packages: mujoco-py
>   Building wheel for mujoco-py (PEP 517) ... error
>   ERROR: Command errored out with exit status 1:
>    command: /Library/Frameworks/Python.framework/Versions/3.8/bin/python3.8 /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/tmpv4_0jd48
>        cwd: /private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py
>   Complete output (49 lines):
>   running bdist_wheel
>   running build
>   Removing old mujoco_py cext /private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/generated/cymj_2.0.2.7_38_macextensionbuilder_38.so
>   Traceback (most recent call last):
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
>       main()
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
>       json_out['return_val'] = hook(**hook_input['kwargs'])
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 181, in build_wheel
>       return _build_backend().build_wheel(wheel_directory, config_settings,
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 208, in build_wheel
>       return self._build_with_temp_dir(['bdist_wheel'], '.whl',
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
>       self.run_setup()
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 236, in run_setup
>       super(_BuildMetaLegacyBackend,
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
>       exec(compile(code, __file__, 'exec'), locals())
>     File "setup.py", line 33, in <module>
>       setup(
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
>       return distutils.core.setup(**attrs)
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 966, in run_commands
>       self.run_command(cmd)
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-build-env-ie6xv95k/normal/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 192, in run
>       self.run_command('build')
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/distutils/dist.py", line 985, in run_command
>       cmd_obj.run()
>     File "setup.py", line 29, in run
>       import mujoco_py  # noqa: force build
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
>       from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 506, in <module>
>       cymj = load_cython_ext(mujoco_path)
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 105, in load_cython_ext
>       cext_so_path = builder.build()
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 221, in build
>       built_so_file_path = self._build_impl()
>     File "/private/var/folders/gg/rh5zmb1x1zqfpsft1whnqwxr0000gn/T/pip-install-en8ndiu2/mujoco-py/mujoco_py/builder.py", line 324, in _build_impl
>       raise RuntimeError(
>   RuntimeError: Could not find GCC executable.
>   
>   HINT: On OS X, install GCC with `brew install gcc`. or `port install gcc`.
>   ----------------------------------------
>   ERROR: Failed building wheel for mujoco-py
>   Running setup.py clean for mujoco-py
> Failed to build mujoco-py
> ERROR: Could not build wheels for mujoco-py which use PEP 517 and cannot be installed directly
> ```

Have you tried following the steps on: https://github.com/openai/mujoco-py?

**Comment by jramirezpr** [comment]
I installed version 9 of gcc, it seems to work with the current pip for mujoco-py:

`brew install gcc@9`

**Comment by kausiksivakumar** [comment]
My gcc is 9.3.0. I still have this problem. I am following this tutorial https://www.chenshiyu.top/blog/2019/06/19/Tutorial-Installation-and-Configuration-of-MuJoCo-Gym-Baselines/ Still no luck

**Comment by kausiksivakumar** [comment]
Now it works, so what I did was follow this https://medium.com/@ganeshprasanna/setting-up-mujoco-7a5ee62cf6dc and do it in a conda virtual env with python 3.6+
Might work for you too.
